import { Card } from "@/components/ui/card"

const Dashboard = () => {
  return (
    <>
      <Card>
        <h1> lorem 555</h1>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iusto harum modi dolores iste odit accusantium eligendi veritatis eaque quaerat, maxime dolor repudiandae voluptates architecto, vero totam. Possimus natus totam dolores tempora molestias illum soluta libero quis debitis ratione qui, at in atque iusto dignissimos, hic sapiente inventore. Libero temporibus nesciunt aperiam quo, harum tenetur dolorum saepe sequi est iste odit voluptate laudantium excepturi nihil minima perferendis cum ab ipsam illo reiciendis laborum ducimus impedit! Eos repellat omnis reprehenderit quae placeat dolore, et eveniet nostrum sequi dolorum architecto amet iusto harum corporis blanditiis quibusdam. Facilis exercitationem itaque aliquid cumque beatae vero cum amet dolorem unde ea id velit quibusdam eligendi, provident quisquam!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi quo illum explicabo impedit suscipit. Corporis, dolores! Fuga quia veritatis fugit at obcaecati corrupti qui aut voluptatibus provident nemo a voluptatum, quaerat mollitia eaque placeat voluptates fugiat dolore atque numquam distinctio recusandae! Ea facilis odio beatae optio deserunt ducimus vel deleniti consequatur iusto dolore quasi natus non doloribus ullam obcaecati, sunt velit, omnis eveniet ipsam sequi delectus mollitia repudiandae minima! Debitis iure nisi eius asperiores soluta dolorum quaerat, perferendis molestias iste voluptas voluptates nesciunt et, commodi possimus in aut ad, ab quod quos illo. Quod, autem corporis ea aut atque ut totam voluptas nesciunt cumque veritatis iusto mollitia accusamus inventore, sequi fugiat!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo quasi autem facere culpa, magnam doloribus, facilis sint at ratione dignissimos, quod ipsam incidunt nam officia obcaecati temporibus quibusdam amet unde ullam possimus. Fugiat in, corporis pariatur iusto cumque numquam maiores. Quod corporis laudantium unde. Deleniti eius, veniam unde laboriosam, iure dignissimos, nemo illo at aspernatur voluptatem sunt consequatur vero dolor sequi labore voluptatibus in repellendus obcaecati illum quasi rem quas laudantium et. Qui optio soluta libero laboriosam facilis, eligendi dicta voluptatum quis consequuntur nostrum ipsum quidem odio itaque quasi explicabo quisquam. Tenetur est iste quia autem quisquam laudantium, eius voluptatem ab maiores nostrum reprehenderit recusandae officia nulla minima nesciunt amet accusamus ducimus ut tempore ratione voluptas aliquid repudiandae eos? Qui sequi velit impedit, placeat architecto mollitia, doloribus, vero necessitatibus odit magnam voluptatem? Eos modi qui, asperiores, praesentium hic perspiciatis corporis autem iure cupiditate cum sequi ipsam recusandae necessitatibus quas ex laboriosam deleniti inventore rerum, quidem eligendi dicta debitis temporibus tenetur. Vitae perspiciatis asperiores praesentium magni eligendi quaerat quos corrupti, culpa, aspernatur non dolore animi quod. Impedit in illum illo libero, placeat adipisci odit quisquam eius mollitia, deleniti similique ipsa voluptates beatae. Eum totam sapiente quo officia quaerat exercitationem accusamus voluptates, similique aspernatur eligendi minima obcaecati in ullam dolore inventore. Corrupti deserunt, eligendi, sequi ipsam quidem quia dicta assumenda architecto exercitationem, temporibus iste?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis eum voluptatibus id, itaque nobis beatae ipsum provident, laborum nam molestiae dolorem fugit porro dignissimos laboriosam rem, minima assumenda repellat sit cupiditate reiciendis quia in mollitia dolores amet? Natus tenetur ea rem repellat maxime doloremque, aliquid iusto nulla esse architecto fuga mollitia harum ipsa. Modi voluptatum, consequatur saepe maiores sapiente ea a nihil, rem eaque laboriosam corrupti dolores error tempore voluptate? Quos sit neque cumque reprehenderit officiis officia facilis nam provident, corporis cupiditate temporibus cum ipsa tempora harum minima vel eius error et hic adipisci iste suscipit dolorum quasi. Ab vitae laudantium soluta, laborum officia cupiditate temporibus iste veritatis ea, obcaecati animi distinctio rerum officiis quaerat exercitationem reiciendis minima voluptate maiores? Placeat, possimus exercitationem laborum in nemo fugit minus, tempore soluta eaque labore assumenda optio aspernatur aperiam maxime esse quibusdam. Et assumenda ex quos corporis illum accusamus, dignissimos quaerat facilis commodi ea itaque repellat unde qui in omnis, laudantium quo tempore quod aut impedit molestias! Est magnam rerum quam eos unde nihil omnis libero iusto, sapiente tenetur dolores perferendis ducimus nostrum. Tempore amet error culpa commodi ratione dolorem id quod esse labore, non doloremque illo dolore maiores omnis rem molestias atque optio reiciendis ea, sunt adipisci dicta? Facilis blanditiis commodi eum animi. Nisi, voluptate! Unde doloremque eaque non ex nemo tempora animi quo.</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique, placeat culpa impedit alias error neque dignissimos. Reprehenderit error eveniet voluptatem modi commodi odio odit dolorum molestias, culpa nemo facere pariatur, placeat nesciunt tempora sit aperiam sunt maiores laborum ut iusto? Ex veritatis incidunt, accusantium animi quia adipisci unde fugit rem, officia dolorem ullam nisi? Hic delectus modi temporibus consequuntur quis maxime odio expedita officiis debitis quo reprehenderit neque consectetur nesciunt quidem cupiditate repellat ipsum aperiam id molestias dignissimos laborum, enim dicta. Expedita maiores nihil dignissimos error totam exercitationem, sit, ipsum pariatur est aliquam, reiciendis voluptatum rem ullam consectetur illum. Corrupti aperiam ad pariatur, molestias labore suscipit quidem porro ea blanditiis amet!</p>
      </Card>
    </>
  )
}

export default Dashboard
